trigger:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Plumbing/core-templates
    - repository: Fleck
      type: git
      name: Open/Fleck

stages:
- template: stages/sync/sync.yml@templates  # Template reference
  parameters:
    checkout: Fleck
